# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x06\x66raude\"t\n\rRequeteFraude\x12\x13\n\x0bid_sinistre\x18\x01 \x01(\t\x12\x11\n\tid_client\x18\x02 \x01(\t\x12\x15\n\rtype_sinistre\x18\x03 \x01(\t\x12\x0f\n\x07montant\x18\x04 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\"Z\n\rReponseFraude\x12\x13\n\x0bid_sinistre\x18\x01 \x01(\t\x12$\n\x06niveau\x18\x02 \x01(\x0e\x32\x14.fraude.NiveauRisque\x12\x0e\n\x06raison\x18\x03 \x01(\t*@\n\x0cNiveauRisque\x12\x0e\n\nNON_DEFINI\x10\x00\x12\n\n\x06\x46\x41IBLE\x10\x01\x12\t\n\x05MOYEN\x10\x02\x12\t\n\x05\x45LEVE\x10\x03\x32X\n\x16ServiceDetectionFraude\x12>\n\x0eVerifierFraude\x12\x15.fraude.RequeteFraude\x1a\x15.fraude.ReponseFraudeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NIVEAURISQUE']._serialized_start=243
  _globals['_NIVEAURISQUE']._serialized_end=307
  _globals['_REQUETEFRAUDE']._serialized_start=33
  _globals['_REQUETEFRAUDE']._serialized_end=149
  _globals['_REPONSEFRAUDE']._serialized_start=151
  _globals['_REPONSEFRAUDE']._serialized_end=241
  _globals['_SERVICEDETECTIONFRAUDE']._serialized_start=309
  _globals['_SERVICEDETECTIONFRAUDE']._serialized_end=397
# @@protoc_insertion_point(module_scope)
